spring:
  datasource:
    username: user
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parts?serverTimezone=UTC&allowPublicKeyRetrieval=true

  session:
    store-type: redis
  redis:
    host: localhost
    password: 123123
    port: 6379